-- =========================================================
-- AI Frontier Club - Full Supabase Migration Schema & Data
-- =========================================================

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  venue TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  image TEXT NOT NULL DEFAULT '',
  registration_link TEXT NOT NULL DEFAULT '',
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'published',
  featured INTEGER NOT NULL DEFAULT 0,
  capacity INTEGER NOT NULL DEFAULT 0,
  webhook_url TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  department TEXT NOT NULL DEFAULT '',
  photo TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  linkedin TEXT NOT NULL DEFAULT '',
  github TEXT NOT NULL DEFAULT '',
  bio TEXT NOT NULL DEFAULT '',
  "order" INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS event_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  team_name TEXT NOT NULL DEFAULT '',
  member1 TEXT NOT NULL DEFAULT '',
  member2 TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  member2_phone TEXT NOT NULL DEFAULT '',
  member2_email TEXT NOT NULL DEFAULT '',
  department TEXT NOT NULL DEFAULT '',
  college TEXT NOT NULL DEFAULT '',
  roll_number TEXT NOT NULL DEFAULT '',
  member2_roll_number TEXT NOT NULL DEFAULT '',
  section TEXT NOT NULL DEFAULT '',
  year TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  attended INTEGER NOT NULL DEFAULT 0,
  checked_in_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure newly added columns exist if table was already created
ALTER TABLE event_registrations ADD COLUMN IF NOT EXISTS section TEXT NOT NULL DEFAULT '';
ALTER TABLE event_registrations ADD COLUMN IF NOT EXISTS member2_email TEXT NOT NULL DEFAULT '';
ALTER TABLE event_registrations ADD COLUMN IF NOT EXISTS member2_roll_number TEXT NOT NULL DEFAULT '';


CREATE TABLE IF NOT EXISTS club_details (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  department TEXT NOT NULL,
  tagline TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  vision TEXT NOT NULL DEFAULT '',
  mission TEXT NOT NULL DEFAULT '',
  founded_year TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  location TEXT NOT NULL DEFAULT '',
  social_links JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS club_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  photo TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT 'Workshop',
  description TEXT NOT NULL DEFAULT '',
  "order" INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE club_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE club_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies (Drop existing if re-running to avoid duplicate policy error)
DO $$
BEGIN
  -- Events
  DROP POLICY IF EXISTS "Public read events" ON events;
  DROP POLICY IF EXISTS "Anon full access events" ON events;
  CREATE POLICY "Public read events" ON events FOR SELECT USING (true);
  CREATE POLICY "Anon full access events" ON events FOR ALL TO anon USING (true) WITH CHECK (true);

  -- Team members
  DROP POLICY IF EXISTS "Public read team_members" ON team_members;
  DROP POLICY IF EXISTS "Anon full access team_members" ON team_members;
  CREATE POLICY "Public read team_members" ON team_members FOR SELECT USING (true);
  CREATE POLICY "Anon full access team_members" ON team_members FOR ALL TO anon USING (true) WITH CHECK (true);

  -- Club details
  DROP POLICY IF EXISTS "Public read club_details" ON club_details;
  DROP POLICY IF EXISTS "Anon full access club_details" ON club_details;
  CREATE POLICY "Public read club_details" ON club_details FOR SELECT USING (true);
  CREATE POLICY "Anon full access club_details" ON club_details FOR ALL TO anon USING (true) WITH CHECK (true);

  -- Club activities
  DROP POLICY IF EXISTS "Public read club_activities" ON club_activities;
  DROP POLICY IF EXISTS "Anon full access club_activities" ON club_activities;
  CREATE POLICY "Public read club_activities" ON club_activities FOR SELECT USING (true);
  CREATE POLICY "Anon full access club_activities" ON club_activities FOR ALL TO anon USING (true) WITH CHECK (true);

  -- Event registrations
  DROP POLICY IF EXISTS "Public register events" ON event_registrations;
  DROP POLICY IF EXISTS "Public lookup ticket" ON event_registrations;
  DROP POLICY IF EXISTS "Anon full access registrations" ON event_registrations;
  CREATE POLICY "Public register events" ON event_registrations FOR INSERT WITH CHECK (true);
  CREATE POLICY "Public lookup ticket" ON event_registrations FOR SELECT USING (true);
  CREATE POLICY "Anon full access registrations" ON event_registrations FOR ALL TO anon USING (true) WITH CHECK (true);

  -- Subscribers
  DROP POLICY IF EXISTS "Public subscribe newsletter" ON subscribers;
  DROP POLICY IF EXISTS "Anon full access subscribers" ON subscribers;
  CREATE POLICY "Public subscribe newsletter" ON subscribers FOR INSERT WITH CHECK (true);
  CREATE POLICY "Anon full access subscribers" ON subscribers FOR ALL TO anon USING (true) WITH CHECK (true);

  -- Settings
  DROP POLICY IF EXISTS "Anon full access settings" ON settings;
  CREATE POLICY "Anon full access settings" ON settings FOR ALL TO anon USING (true) WITH CHECK (true);
END $$;

-- 4. Initial Seed Data

-- Events Seed
INSERT INTO events (id, title, slug, date, end_date, venue, description, summary, image, registration_link, tags, status, featured, capacity, webhook_url)
VALUES (4, 'AI Frontiers Club', 'ai-frontiers-club', '2026-09-26T08:30:00.000Z'::timestamptz, NULL, 'LAB 5', 'Welcome to AI Frontiers Hackathon 2026! A premier collegiate 2-member team buildathon challenging students to design, prototype, and deploy real-world Artificial Intelligence systems.

Event Schedule & Agenda:
• 08:30 AM - 09:15 AM : Reporting, Check-In & Team Badge Distribution
• 09:15 AM - 10:00 AM : Keynote Address & Problem Statements Release
• 10:00 AM - 01:00 PM : Phase 1: Architecture Ideation & Data Pipeline
• 01:00 PM - 01:45 PM : Networking & Lunch Break
• 01:45 PM - 04:00 PM : Phase 2: Core Model Building & Frontend Integration
• 04:00 PM - 05:30 PM : Final Pitch Deck & Live Project Demonstration
• 05:30 PM - 06:00 PM : Valedictory Ceremony & Prize Distribution', 'Premier 2-member AI buildathon with model prototyping, live pitches, and mentorship.', '', '', '["AI","Hackathon","Coding"]'::jsonb, 'published', 0, 60, '')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, summary = EXCLUDED.summary;

-- Team Members Seed
INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (1, 'Dr. K. Manivannan', 'Coordinator', 'HoD, AI&DS', '', 'hod.aids@college.edu', '', '', '', 'Head of Department guiding academic innovation, research projects, and student learning at AI Frontier Club.', 1, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (2, 'Mrs. V. Kavitha', 'Coordinator', 'HoD, AI&DS', '', 'kavitha.aids@college.edu', '', '', '', 'Head of Department guiding academic innovation, research projects, and student learning at AI Frontier Club.', 2, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (3, 'Mrs. B. Bharathi', 'Assistant Coordinator', 'AP / AI&DS', '', 'bharathi.aids@college.edu', '', '', '', 'Assistant Professor mentoring technical workshops, project exhibitions, and departmental club activities.', 3, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (4, 'Ram Pradeep R P', 'Students Overall Coordinator', 'III - AI&DS', '', 'rampradeep@aifrontierclub.org', '63797 52463', 'https://www.linkedin.com/in/r-p-ram-pradeep', 'https://github.com/Rampradeep31', 'Leading overall club initiatives, hackathon delegations, and student technical chapters.', 4, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (5, 'Ragav U', 'Students Overall Coordinator', 'III - AI&DS', '', 'coordinator@aifrontierclub.org', '+919360376757', 'https://www.linkedin.com/in/ragav-u/', 'https://github.com/RagavU1430', 'Leading full-stack AI development, community initiatives, and competitive coding.', 5, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (6, 'Keerthana B', 'Third Year Coordinator', 'III - AI&DS', '', '', '', '', '', 'Coordinating third-year student programs, technical bootcamps, and club project tracks.', 6, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (7, 'Ragul M', 'Third Year Coordinator', 'III - AI&DS', '', '', '96004 21157', 'https://www.linkedin.com/in/ragul-m-354a49339/', '', 'Coordinating third-year student initiatives, hands-on lab sessions, and digital events.', 7, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (8, 'Suriya R', 'Second Year Coordinator', 'II - AI&DS', '', '', '', '', '', 'Facilitating second-year student engagement, workshops, and AI project teams.', 8, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (9, 'Keerthi Dharani G', 'Second Year Coordinator', 'II - AI&DS', '', '', '', '', '', 'Managing second-year coordinator outreach, peer learning sessions, and club activities.', 9, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (10, 'Nithya Shree C', 'First Year Coordinator', 'I - AI&DS', '', '', '', '', '', 'Welcoming first-year students, introducing AI fundamentals, and coordinating junior hackathon teams.', 10, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (11, 'Dhakshina Moorthy M', 'First Year Coordinator', 'I - AI&DS', '', '', '', '', '', 'Coordinating first-year student onboarding, coding sessions, and event participation.', 11, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

-- Club Details Seed
INSERT INTO club_details (id, name, department, tagline, description, vision, mission, founded_year, email, phone, location, social_links)
VALUES (1, 'AI Frontier Club', 'Artificial Intelligence & Data Science', 'Where Curious Minds Learn, Code, and Build with AI', 'The premier collegiate student & developer guild exploring, learning, and building with Artificial Intelligence and Data Science.', 'To empower students to master artificial intelligence through hands-on coding, open-source projects, and collaborative hackathons.', 'Equip students with deep learning, machine learning, and computer vision skills to build high-impact real-world systems.', '2021', 'contact@aifrontierclub.org', '+91 98765 43210', 'Center for AI Excellence, Department of AI & DS', '{"linkedin":"https://linkedin.com","github":"https://github.com","instagram":"https://instagram.com","discord":"https://discord.gg"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- Settings Seed
INSERT INTO settings (key, value)
VALUES ('google_sheet_url', 'https://docs.google.com/spreadsheets/d/1MUkixf7X2_5cYzZJm1dL1atzRK2sIPxLpgKDGV7rTYk/edit?usp=sharing')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO settings (key, value)
VALUES ('google_sheet_id', '1MUkixf7X2_5cYzZJm1dL1atzRK2sIPxLpgKDGV7rTYk')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO settings (key, value)
VALUES ('google_sheet_webhook_url', 'https://script.google.com/macros/s/AKfycbwM2P5GG8BQP-OWEZHo3IMlYHoD5NVCUJeZclRWeR_Q6u8V4fGno1xb3tMLg6tJRh3m/exec')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO settings (key, value)
VALUES ('gmail_user', '')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO settings (key, value)
VALUES ('gmail_app_password', '')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO settings (key, value)
VALUES ('email_sender_name', 'AI Frontier Club')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Event Registrations Seed
INSERT INTO event_registrations (id, event_id, team_name, member1, member2, name, email, phone, member2_phone, department, college, roll_number, year, notes, attended, checked_in_at)
VALUES (9, 4, 'TEST TEAM', 'TEST NAME 1', 'TEST NAME 2', 'TEST NAME 1', 'lead@example.com', '', 'member2@example.com', 'Artificial Intelligence and Data Science', 'Artificial Intelligence and Data Science', '', '2nd Year', '', 1, '2026-09-18T04:58:27.130Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO event_registrations (id, event_id, team_name, member1, member2, name, email, phone, member2_phone, department, college, roll_number, year, notes, attended, checked_in_at)
VALUES (10, 4, 'Neural Knights', 'Sabesh E', 'Ram Pradeep RP', 'Sabesh E', 'sabeshsabesh082007@gmail.com', '', 'rampradeep4858@gmail.com', 'Artificial Intelligence and Data Science', 'Artificial Intelligence and Data Science', '', '3rd Year', '', 1, '2026-09-18T04:58:34.889Z'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO event_registrations (id, event_id, team_name, member1, member2, name, email, phone, member2_phone, department, college, roll_number, year, notes, attended, checked_in_at)
VALUES (11, 4, 'Debug Team', 'Test User', '', 'Test User', 'test@example.com', '1234567890', '', 'AI', 'AI', '', '3rd', '', 0, NULL)
ON CONFLICT (id) DO NOTHING;

-- 5. Auto-Increment Sequences
DO $$
BEGIN
  IF pg_get_serial_sequence('events', 'id') IS NOT NULL THEN
    PERFORM setval(pg_get_serial_sequence('events', 'id'), (SELECT COALESCE(MAX(id), 1) FROM events));
  END IF;
  IF pg_get_serial_sequence('team_members', 'id') IS NOT NULL THEN
    PERFORM setval(pg_get_serial_sequence('team_members', 'id'), (SELECT COALESCE(MAX(id), 1) FROM team_members));
  END IF;
  IF pg_get_serial_sequence('event_registrations', 'id') IS NOT NULL THEN
    PERFORM setval(pg_get_serial_sequence('event_registrations', 'id'), (SELECT COALESCE(MAX(id), 1) FROM event_registrations));
  END IF;
END $$;

-- 6. Supabase Storage: Public Bucket & RLS Policies for club-uploads
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('club-uploads', 'club-uploads', true, 10485760, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
ON CONFLICT (id) DO UPDATE SET public = true;

DO $$
BEGIN
  DROP POLICY IF EXISTS "Public select club-uploads" ON storage.objects;
  DROP POLICY IF EXISTS "Public insert club-uploads" ON storage.objects;
  DROP POLICY IF EXISTS "Public update club-uploads" ON storage.objects;
  DROP POLICY IF EXISTS "Public delete club-uploads" ON storage.objects;

  CREATE POLICY "Public select club-uploads"
    ON storage.objects FOR SELECT
    TO public
    USING (bucket_id = 'club-uploads');

  CREATE POLICY "Public insert club-uploads"
    ON storage.objects FOR INSERT
    TO public
    WITH CHECK (bucket_id = 'club-uploads');

  CREATE POLICY "Public update club-uploads"
    ON storage.objects FOR UPDATE
    TO public
    USING (bucket_id = 'club-uploads');

  CREATE POLICY "Public delete club-uploads"
    ON storage.objects FOR DELETE
    TO public
    USING (bucket_id = 'club-uploads');
END $$;

