-- =========================================================
-- AI Frontier Club - Full Supabase Migration Schema & Data
-- =========================================================

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  venue TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  image TEXT NOT NULL DEFAULT '',
  registration_link TEXT NOT NULL DEFAULT '',
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'published',
  featured INTEGER NOT NULL DEFAULT 0,
  capacity INTEGER NOT NULL DEFAULT 0,
  webhook_url TEXT DEFAULT '',
  agenda_url TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  department TEXT NOT NULL DEFAULT '',
  photo TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  linkedin TEXT NOT NULL DEFAULT '',
  github TEXT NOT NULL DEFAULT '',
  bio TEXT NOT NULL DEFAULT '',
  "order" INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS event_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  team_name TEXT NOT NULL DEFAULT '',
  member1 TEXT NOT NULL DEFAULT '',
  member2 TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  member2_phone TEXT NOT NULL DEFAULT '',
  member2_email TEXT NOT NULL DEFAULT '',
  department TEXT NOT NULL DEFAULT '',
  college TEXT NOT NULL DEFAULT '',
  roll_number TEXT NOT NULL DEFAULT '',
  member2_roll_number TEXT NOT NULL DEFAULT '',
  section TEXT NOT NULL DEFAULT '',
  year TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  attended INTEGER NOT NULL DEFAULT 0,
  checked_in_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure newly added columns exist if table was already created
ALTER TABLE events ADD COLUMN IF NOT EXISTS agenda_url TEXT DEFAULT '';
ALTER TABLE event_registrations ADD COLUMN IF NOT EXISTS section TEXT NOT NULL DEFAULT '';
ALTER TABLE event_registrations ADD COLUMN IF NOT EXISTS member2_email TEXT NOT NULL DEFAULT '';
ALTER TABLE event_registrations ADD COLUMN IF NOT EXISTS member2_roll_number TEXT NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_registrations_event_email ON event_registrations(event_id, lower(email));


CREATE TABLE IF NOT EXISTS club_details (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  department TEXT NOT NULL,
  tagline TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  vision TEXT NOT NULL DEFAULT '',
  mission TEXT NOT NULL DEFAULT '',
  founded_year TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  location TEXT NOT NULL DEFAULT '',
  social_links JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS club_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  photo TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT 'Workshop',
  description TEXT NOT NULL DEFAULT '',
  "order" INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Event games (played by verified registered participants)
CREATE TABLE IF NOT EXISTS games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  game_url TEXT NOT NULL DEFAULT '',
  event_id BIGINT REFERENCES events(id) ON DELETE SET NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  is_live INTEGER NOT NULL DEFAULT 0,
  "order" INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE games ADD COLUMN IF NOT EXISTS is_live INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE club_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE club_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE games ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies (Drop existing if re-running to avoid duplicate policy error)
DO $$
BEGIN
  -- Events
  DROP POLICY IF EXISTS "Public read events" ON events;
  DROP POLICY IF EXISTS "Anon full access events" ON events;
  DROP POLICY IF EXISTS "Authenticated manage events" ON events;
  CREATE POLICY "Public read events" ON events FOR SELECT USING (true);
  CREATE POLICY "Authenticated manage events" ON events FOR ALL TO authenticated USING (true) WITH CHECK (true);

  -- Team members
  DROP POLICY IF EXISTS "Public read team_members" ON team_members;
  DROP POLICY IF EXISTS "Anon full access team_members" ON team_members;
  DROP POLICY IF EXISTS "Authenticated manage team_members" ON team_members;
  CREATE POLICY "Public read team_members" ON team_members FOR SELECT USING (true);
  CREATE POLICY "Authenticated manage team_members" ON team_members FOR ALL TO authenticated USING (true) WITH CHECK (true);

  -- Club details
  DROP POLICY IF EXISTS "Public read club_details" ON club_details;
  DROP POLICY IF EXISTS "Anon full access club_details" ON club_details;
  DROP POLICY IF EXISTS "Authenticated manage club_details" ON club_details;
  CREATE POLICY "Public read club_details" ON club_details FOR SELECT USING (true);
  CREATE POLICY "Authenticated manage club_details" ON club_details FOR ALL TO authenticated USING (true) WITH CHECK (true);

  -- Club activities
  DROP POLICY IF EXISTS "Public read club_activities" ON club_activities;
  DROP POLICY IF EXISTS "Anon full access club_activities" ON club_activities;
  DROP POLICY IF EXISTS "Authenticated manage club_activities" ON club_activities;
  CREATE POLICY "Public read club_activities" ON club_activities FOR SELECT USING (true);
  CREATE POLICY "Authenticated manage club_activities" ON club_activities FOR ALL TO authenticated USING (true) WITH CHECK (true);

  -- Games (verified participants read; admins manage)
  DROP POLICY IF EXISTS "Public read games" ON games;
  DROP POLICY IF EXISTS "Authenticated manage games" ON games;
  CREATE POLICY "Public read games" ON games FOR SELECT USING (true);
  CREATE POLICY "Authenticated manage games" ON games FOR ALL TO authenticated USING (true) WITH CHECK (true);

  -- Event registrations
  DROP POLICY IF EXISTS "Public register events" ON event_registrations;  DROP POLICY IF EXISTS "Public lookup ticket" ON event_registrations;
  DROP POLICY IF EXISTS "Anon full access registrations" ON event_registrations;
  DROP POLICY IF EXISTS "Authenticated manage registrations" ON event_registrations;
  CREATE POLICY "Public register events" ON event_registrations FOR INSERT WITH CHECK (true);
  CREATE POLICY "Authenticated manage registrations" ON event_registrations FOR ALL TO authenticated USING (true) WITH CHECK (true);

  -- Subscribers
  DROP POLICY IF EXISTS "Public subscribe newsletter" ON subscribers;
  DROP POLICY IF EXISTS "Anon full access subscribers" ON subscribers;
  DROP POLICY IF EXISTS "Authenticated manage subscribers" ON subscribers;
  CREATE POLICY "Public subscribe newsletter" ON subscribers FOR INSERT WITH CHECK (true);
  CREATE POLICY "Authenticated manage subscribers" ON subscribers FOR ALL TO authenticated USING (true) WITH CHECK (true);

  -- Settings
  DROP POLICY IF EXISTS "Anon full access settings" ON settings;
  DROP POLICY IF EXISTS "Authenticated manage settings" ON settings;
  CREATE POLICY "Authenticated manage settings" ON settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
END $$;

-- Public ticket lookup returns only the requested participant's ticket fields.
CREATE OR REPLACE FUNCTION lookup_registration_tickets(lookup_identifier TEXT, target_event_id BIGINT DEFAULT NULL)
RETURNS TABLE (
  id BIGINT, event_id BIGINT, team_name TEXT, member1 TEXT, member2 TEXT, name TEXT,
  email TEXT, phone TEXT, department TEXT, year TEXT, attended INTEGER,
  checked_in_at TIMESTAMPTZ, event_title TEXT, event_date TIMESTAMPTZ, event_venue TEXT
)
LANGUAGE sql SECURITY DEFINER SET search_path = public
AS $$
  SELECT r.id, r.event_id, r.team_name, r.member1, r.member2, r.name, r.email,
         r.phone, r.department, r.year, r.attended, r.checked_in_at,
         e.title, e.date, e.venue
  FROM event_registrations r
  JOIN events e ON e.id = r.event_id
  WHERE (lower(r.email) = lower(lookup_identifier)
         OR lower(r.member2_email) = lower(lookup_identifier)
         OR (lookup_identifier ~ '^aif-[0-9]+-[0-9]+$'
             AND r.id = split_part(lookup_identifier, '-', 3)::BIGINT))
    AND (target_event_id IS NULL OR r.event_id = target_event_id)
  ORDER BY r.created_at DESC;
$$;

REVOKE ALL ON FUNCTION lookup_registration_tickets(TEXT, BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION lookup_registration_tickets(TEXT, BIGINT) TO anon, authenticated;

-- 4. Initial Seed Data

-- NOTE: No demo events are seeded. Create events from the Admin portal
-- (Events & Registrations → Create New Event) so only real events exist.

-- Team Members Seed
INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (1, 'Dr. K. Manivannan', 'Coordinator', 'HoD, AI&DS', '', 'hod.aids@college.edu', '', '', '', 'Head of Department guiding academic innovation, research projects, and student learning at AI Frontier Club.', 1, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (2, 'Mrs. V. Kavitha', 'Coordinator', 'HoD, AI&DS', '', 'kavitha.aids@college.edu', '', '', '', 'Head of Department guiding academic innovation, research projects, and student learning at AI Frontier Club.', 2, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (3, 'Mrs. B. Bharathi', 'Assistant Coordinator', 'AP / AI&DS', '', 'bharathi.aids@college.edu', '', '', '', 'Assistant Professor mentoring technical workshops, project exhibitions, and departmental club activities.', 3, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (4, 'Ram Pradeep R P', 'Students Overall Coordinator', 'III - AI&DS', '', 'rampradeep@aifrontierclub.org', '63797 52463', 'https://www.linkedin.com/in/r-p-ram-pradeep', 'https://github.com/Rampradeep31', 'Leading overall club initiatives, hackathon delegations, and student technical chapters.', 4, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (5, 'Ragav U', 'Students Overall Coordinator', 'III - AI&DS', '', 'coordinator@aifrontierclub.org', '+919360376757', 'https://www.linkedin.com/in/ragav-u/', 'https://github.com/RagavU1430', 'Leading full-stack AI development, community initiatives, and competitive coding.', 5, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (6, 'Keerthana B', 'Third Year Coordinator', 'III - AI&DS', '', '', '', '', '', 'Coordinating third-year student programs, technical bootcamps, and club project tracks.', 6, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (7, 'Ragul M', 'Third Year Coordinator', 'III - AI&DS', '', '', '96004 21157', 'https://www.linkedin.com/in/ragul-m-354a49339/', '', 'Coordinating third-year student initiatives, hands-on lab sessions, and digital events.', 7, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (8, 'Suriya R', 'Second Year Coordinator', 'II - AI&DS', '', '', '', '', '', 'Facilitating second-year student engagement, workshops, and AI project teams.', 8, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (9, 'Keerthi Dharani G', 'Second Year Coordinator', 'II - AI&DS', '', '', '', '', '', 'Managing second-year coordinator outreach, peer learning sessions, and club activities.', 9, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (10, 'Nithya Shree C', 'First Year Coordinator', 'I - AI&DS', '', '', '', '', '', 'Welcoming first-year students, introducing AI fundamentals, and coordinating junior hackathon teams.', 10, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

INSERT INTO team_members (id, name, role, department, photo, email, phone, linkedin, github, bio, "order", active)
VALUES (11, 'Dhakshina Moorthy M', 'First Year Coordinator', 'I - AI&DS', '', '', '', '', '', 'Coordinating first-year student onboarding, coding sessions, and event participation.', 11, 1)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, department = EXCLUDED.department, bio = EXCLUDED.bio, "order" = EXCLUDED."order";

-- Club Details Seed
INSERT INTO club_details (id, name, department, tagline, description, vision, mission, founded_year, email, phone, location, social_links)
VALUES (1, 'AI Frontier Club', 'Artificial Intelligence & Data Science', 'Where Curious Minds Learn, Code, and Build with AI', 'The premier collegiate student & developer guild exploring, learning, and building with Artificial Intelligence and Data Science.', 'To empower students to master artificial intelligence through hands-on coding, open-source projects, and collaborative hackathons.', 'Equip students with deep learning, machine learning, and computer vision skills to build high-impact real-world systems.', '2021', 'contact@aifrontierclub.org', '+91 98765 43210', 'Center for AI Excellence, Department of AI & DS', '{"linkedin":"https://linkedin.com","github":"https://github.com","instagram":"https://instagram.com","discord":"https://discord.gg"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- Settings Seed
INSERT INTO settings (key, value)
VALUES ('google_sheet_url', 'https://docs.google.com/spreadsheets/d/1MUkixf7X2_5cYzZJm1dL1atzRK2sIPxLpgKDGV7rTYk/edit?usp=sharing')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO settings (key, value)
VALUES ('google_sheet_id', '1MUkixf7X2_5cYzZJm1dL1atzRK2sIPxLpgKDGV7rTYk')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO settings (key, value)
VALUES ('google_sheet_webhook_url', 'https://script.google.com/macros/s/AKfycbwM2P5GG8BQP-OWEZHo3IMlYHoD5NVCUJeZclRWeR_Q6u8V4fGno1xb3tMLg6tJRh3m/exec')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO settings (key, value)
VALUES ('gmail_user', '')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO settings (key, value)
VALUES ('gmail_app_password', '')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO settings (key, value)
VALUES ('email_sender_name', 'AI Frontier Club')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- NOTE: No demo registrations are seeded. All registrations come from the
-- live registration form only, so the database contains real data.

-- 5. Auto-Increment Sequences
DO $$
BEGIN
  IF pg_get_serial_sequence('events', 'id') IS NOT NULL THEN
    PERFORM setval(pg_get_serial_sequence('events', 'id'), (SELECT COALESCE(MAX(id), 1) FROM events));
  END IF;
  IF pg_get_serial_sequence('team_members', 'id') IS NOT NULL THEN
    PERFORM setval(pg_get_serial_sequence('team_members', 'id'), (SELECT COALESCE(MAX(id), 1) FROM team_members));
  END IF;
  IF pg_get_serial_sequence('event_registrations', 'id') IS NOT NULL THEN
    PERFORM setval(pg_get_serial_sequence('event_registrations', 'id'), (SELECT COALESCE(MAX(id), 1) FROM event_registrations));
  END IF;
  IF pg_get_serial_sequence('games', 'id') IS NOT NULL THEN
    PERFORM setval(pg_get_serial_sequence('games', 'id'), (SELECT COALESCE(MAX(id), 1) FROM games));
  END IF;
END $$;

-- 6. Supabase Storage: Public Bucket & RLS Policies for club-uploads
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('club-uploads', 'club-uploads', true, 10485760, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'])
ON CONFLICT (id) DO UPDATE SET public = true, allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];

DO $$
BEGIN
  DROP POLICY IF EXISTS "Public select club-uploads" ON storage.objects;
  DROP POLICY IF EXISTS "Public insert club-uploads" ON storage.objects;
  DROP POLICY IF EXISTS "Public update club-uploads" ON storage.objects;
  DROP POLICY IF EXISTS "Public delete club-uploads" ON storage.objects;
  DROP POLICY IF EXISTS "Authenticated insert club-uploads" ON storage.objects;
  DROP POLICY IF EXISTS "Authenticated update club-uploads" ON storage.objects;
  DROP POLICY IF EXISTS "Authenticated delete club-uploads" ON storage.objects;

  CREATE POLICY "Public select club-uploads"
    ON storage.objects FOR SELECT
    TO public
    USING (bucket_id = 'club-uploads');

  CREATE POLICY "Authenticated insert club-uploads"
    ON storage.objects FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'club-uploads');

  CREATE POLICY "Authenticated update club-uploads"
    ON storage.objects FOR UPDATE
    TO authenticated
    USING (bucket_id = 'club-uploads');

  CREATE POLICY "Authenticated delete club-uploads"
    ON storage.objects FOR DELETE
    TO authenticated
    USING (bucket_id = 'club-uploads');
END $$;

